version: '3'
services:

  app:
    build: .
    ports:
      - 8000:4000
    volumes:
      - ./chinese_ausweis_viewer:/src
    command: gunicorn -b 0.0.0.0:4000 src.app:app --chdir / --reload
    environment:
      - PYTHONUNBUFFERED=1
